### ISSUE TITLE
The 'location' property is not allowed for XX at resource group scope

### ISSUE THREAD

**Issue by ahmedsza** [Azure/appservice-landing-zone-accelerator#139]
I am trying to run this using the instructions but get this error
{"code": "InvalidDeployment", "message": "The 'location' property is not allowed for 'XXXXX' at resource group scope

Any ideas? 

I did set the       "ResourceGroupLocation": {
        "value": "West Europe"

in the parameters file

**Comment by ahmedsza** [comment]
This is for the multitenant secure version using bicep

**Comment by thotheod** [comment]
Hi @ahmedsza. Can you please give more details on what the issue is?
Did you add any new parameter in the [main.parameter.jsonc file](https://github.com/Azure/appservice-landing-zone-accelerator/blob/main/scenarios/secure-baseline-multitenant/bicep/main.parameters.jsonc)? I can't find any ResourceGroupLocation parameter there.

Did you follow [deployment instructions as described here](https://github.com/Azure/appservice-landing-zone-accelerator/tree/main/scenarios/secure-baseline-multitenant/bicep#bash-shell-ie-inside-wsl2-for-windows-11-or-any-linux-based-os)

**Comment by ahmedsza** [comment]
Thanks @thotheod . I honestly don't know what happened. I cloned the repo again in a clean dir - and ran it again - and all is good.  So this can be closed.
